// Code generated by scripts/dev/gen-builtin-plugins.sh; DO NOT EDIT.
// blank-import 触发各插件包 init() 里的 sdk.RegisterBuiltin 自注册。
package builtin

import (
	_ "roam-plugins/cron"
	_ "roam-plugins/hostmonitor"
	_ "roam-plugins/im"
	_ "roam-plugins/keepalive"
	_ "roam-plugins/reviewmesh"
)
